version: "3.9"

services:
  apache:
    container_name: "apache"
    image: apache:latest
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./httpd.conf:/etc/apache2/httpd.conf
      - ./html/:/var/www/html/
      - /docker/etc/letsencrypt/live/waspscripts.com/cert.pem:/etc/letsencrypt/live/waspscripts.com/cert.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/fullchain.pem:/etc/letsencrypt/live/waspscripts.com/fullchain.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/privkey.pem:/etc/letsencrypt/live/waspscripts.com/privkey.pem
      - /docker/server/logs/:/var/www/logs/
    networks:
      - proxy
    environment:
      - USER=torwent
      - SERVER=waspscripts.com

networks:
  proxy:
    driver: bridge
