version: "3.9"

services:
  wasp-server:
    container_name: "wasp-server"
    image: apache:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./httpd.conf:/etc/apache2/httpd.conf
      - ./html/:/var/www/html/
      - /docker/etc/letsencrypt/live/waspscripts.com/cert.pem:/etc/letsencrypt/live/waspscripts.com/cert.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/fullchain.pem:/etc/letsencrypt/live/waspscripts.com/fullchain.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/privkey.pem:/etc/letsencrypt/live/waspscripts.com/privkey.pem
      - /docker/server/logs/:/var/www/logs/
    networks:
      - wasp-proxy
    environment:
      - USER=${USER}
      - SERVER=${SERVER}
      - PASSWORD=${PASSWORD}

networks:
  wasp-proxy:
    external: true
