version: "3.9"
services:
  apache-setup:
    container_name: "apache-setup"
    image: apache-setup:latest
    build:
      context: .
    ports: "80:80"
    volumes:
      - ./httpd.conf:/etc/apache2/httpd.conf
      - ./html:/var/www/localhost/htdocs/
    environment:
      - USER=torwent
      - SERVER=waspscripts.com
